---
title: "integration_subset"
author: "mb_vasques"
date: "2025-06-03"
output: html_document
---

Load necessary packages

```{r}
# data manipulation
library(Seurat)
library(SeuratData)
library(Matrix)
library(dplyr)

# integreation
library(harmony)

# clustering
library(clustree)

# fast DE
library(presto)

# gene set enrichment
library(gprofiler2)

# plotting
library(ggplot2)
library(patchwork)
library(gplots)
library(cowplot)

# palette
library(MetBrewer)

set.seed(1)
```



```{r}
subset = readRDS("/Users/maria/OneDrive/Documentos/iMM/analysis/results/RDS/harmony_subset_srat.RDS")
```


```{r}
sampletype_df = c(
  "D104T11" = "d6_Mix(Treg+Tfh)",
  "D104T13" = "d11_Treg",
  "D104T14" = "d11_Tfh",
  "D104T15" = "d11_Tfr",
  "D104T16" = "d0_Treg",
  "hCD2_d0_Treg" = "d0_Treg",
  "hCD2_d6_Tfr" = "d6_Tfr",
  "hCD2_d11_Tfr" = "d11_Tfr"
)

subset$sample_type = unname(sampletype_df[subset$orig.ident])
```


```{r}
head(subset@meta.data)
```



```{r}
# srat_filt = D104T11_final_srat.RDS (final annotation)

# Assign the cell type annotation to D104T11 cells
subset@meta.data[rownames(srat_subset@meta.data), "cell_type"] = srat_subset$cell_type
subset@meta.data[rownames(srat_subset@meta.data), "D104T11_annotation"] = srat_subset$D104T11_annotation
```


```{r}
subset = NormalizeData(subset, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
subset = FindVariableFeatures(subset, selection.method = "vst", nfeatures = 5000)
```


```{r, fig.width=10, fig.height=8}
# Identify the 20 most highly variable genes
top20 = head(VariableFeatures(subset), 20)

# plot variable features with and without labels
plot1 = VariableFeaturePlot(subset)
plot2 = LabelPoints(plot = plot1, points = top20, repel = TRUE)
plot2
```


```{r}
subset = ScaleData(subset, vars.to.regress = c("nCount_RNA", "percent.mt", "percent.rb"), do.scale = F)
```


```{r}
subset
```


```{r}
subset = RunPCA(subset, verbose = T, assay = "RNA", npcs = 50)
ep = ElbowPlot(subset, ndims = 50)
print(ep)
```


```{r}
ncomp = 30
subset = RunHarmony(subset, group.by.vars = "experiment", dims.use = 1:ncomp, max_iter = 50)
```


```{r}
ncomp = 20
subset = RunUMAP(subset, reduction = "harmony", dims = 1:ncomp, seed.use = 42)
```


```{r}
UMAPPlot(subset, group.by="experiment")
```

```{r}
DimPlot(subset, reduction = "umap", group.by = "Phase")
```


```{r}
UMAPPlot(subset, group.by="cell_type")
```


```{r fig.width= 18, fig.height=17}
FeaturePlot(subset, features = c("Tigit","Foxp3","Cxcr5","Icos","Gzmb","Il2ra",
                                  "Ccr7","Bcl6","Sh2d1a","Sell","Il1r2","Cd40lg"), 
            order=T, pt.size = 0.8, ncol = 3)
```


```{r}
red = "harmony"
ncomp = 20
subset = FindNeighbors(subset, dims = 1:ncomp, force.recalc = T, verbose = T,
                          reduction = red, compute.SNN = T,
                          graph.name = c(paste0("NN_", red, ncomp),
                                         paste0("SNN_", red, ncomp)))
```


```{r}
subset = FindClusters(subset, algorithm = 2, verbose = T, 
                         graph.name = paste0("SNN_", red, ncomp),
                         resolution = seq(0.2, 1, 0.1))

# setting a more sensible identity as default
subset = SetIdent(subset, value = paste0("SNN_", red, ncomp, "_res.0.3"))
```


```{r, fig.width=10, fig.height=10}
plt_list = list()
# iterate each clustering resolution
for(cl in colnames(subset@meta.data)[grepl("SNN_harmony20_", colnames(subset@meta.data))]){
subset = SetIdent(subset, value = cl) # set the resolution as default identity

plt_list[[cl]] = DimPlot(subset, reduction = "umap",
                         label = T, raster = F, pt.size = 0.2, shuffle = T)+
    labs(subtitle = cl)+
    theme(legend.position = "none",
          aspect.ratio = 1)
} #generate UMAPs 

cowplot::plot_grid(plotlist = plt_list, ncol = 3)

# as we increase the resolution we get more clusters, note that clustering isn't done in the umap (umap is simply a dimensionality reduction technique)
```


```{r fig.width=8, fig.height=10}
clustree(subset, prefix = "SNN_harmony20_res.")
```


```{r fig.width=12, fig.height=5}
pal = met.brewer("Klimt", 10)
DimPlot(subset, group.by = c("SNN_harmony20_res.0.3","SNN_harmony20_res.0.4"), 
        pt.size = 0.8, label = T, label.size = 12, ncol = 2, cols = pal)
```


```{r fig.width=18, fig.height=5}
DimPlot(subset, group.by = c("SNN_harmony20_res.0.4","SNN_harmony20_res.0.5","SNN_harmony20_res.0.6"), 
        pt.size = 0.8, label = T, label.size = 12, ncol = 3, cols = pal)
```




```{r fig.width=16, fig.height=10}
DimPlot(subset, group.by = "SNN_harmony20_res.0.6", split.by = "sample_type",
        pt.size = 0.8, label.size = 12, cols = pal, ncol = 3)
```


```{r fig.width=16, fig.height=12}
DimPlot(subset, group.by = "SNN_harmony20_res.0.6", split.by = "cell_type",
        pt.size = 1.2, label.size = 12, cols = pal, ncol = 2)
```


```{r}
counts_df <- subset@meta.data %>%
  group_by(SNN_harmony20_res.0.6, cell_type) %>%
  summarise(count = n(), .groups = "drop")

ggplot(counts_df, aes(x = SNN_harmony20_res.0.6, y = count, fill = cell_type)) +
  geom_bar(stat = "identity", position = "stack") +
  ylab("Number of Cells") +
  xlab("Cluster") +
  theme_minimal() +
  labs(fill = "cell_type")
```


```{r fig.width=15, fig.height=5}
UMAPPlot(subset, group.by="cell_type", split.by="day")
```


```{r fig.width=10, fig.height=5}
UMAPPlot(subset, group.by="cell_type", split.by="experiment")
```


```{r fig.width=11, fig.height=5}
DimPlot(subset, group.by = "SNN_harmony20_res.0.6", split.by = "experiment",
        pt.size = 1, cols = pal)
```


```{r fig.width=16, fig.height=8}
DimPlot(subset, group.by = "SNN_harmony20_res.0.6", split.by = "orig.ident",
        pt.size = 0.8, label.size = 12, cols = pal, ncol = 4)
```

```{r fig.width=16, fig.height=8}
DimPlot(subset, group.by = "SNN_harmony20_res.0.6", split.by = "sample_type",
        pt.size = 0.8, label.size = 12, cols = pal, ncol = 3)
```


```{r fig.width=16, fig.height=5}
DimPlot(subset, group.by = "SNN_harmony20_res.0.6", split.by = "cell_type",
        pt.size = 0.8, label.size = 12, cols = pal)
```

```{r fig.width=16, fig.height=10}
FeaturePlot(subset, features = c("nCount_RNA", "nFeature_RNA","percent.mt","percent.rb"),
            order=T, ncol = 2)
```


```{r fig.width=6, fig.height=8}
# Treg: "Foxp3","Prdm1","Klf2","Sell","S1pr1","Ccr7","Il2ra","Selplg","Ctla4","Gzmb","Ccr2","Tnfrsf18","Tnfrsf4","Icos"
# Tfh: "Tigit","Sh2d1a","Pdcd1","Bcl6","Cxcr5","Il4","Il21","Maf","Gpr183","Cd40lg"
# Tfr: "Il1r2"
# Exhausted T cells: "Havcr2","Lag3","Btla"

markers = c("Foxp3","Prdm1","Klf2","Sell","S1pr1","Ccr7","Il2ra","Selplg","Ctla4",
            "Gzmb","Ccr2","Tnfrsf18","Tnfrsf4","Icos","Tigit","Sh2d1a","Pdcd1",
            "Bcl6","Cxcr5","Il4","Il21","Maf","Gpr183","Cd40lg","Il1r2")

cl_use = "SNN_harmony20_res.0.6" 
DotPlot(subset, features = markers, 
        assay = "RNA",
        group.by = cl_use) +
  coord_flip() +
  scale_color_gradientn(colors = colorRampPalette(met.brewer("Johnson", direction = -1))(100))
```


```{r fig.width=6, fig.height=5}
DimPlot(subset, group.by = c("SNN_harmony20_res.0.6"), 
        pt.size = 0.8, label = T, label.size = 12, cols = pal)
```


```{r fig.width=6, fig.height=8}
markers = c("Foxp3","Prdm1","Klf2","Sell","S1pr1","Ccr7","Smad7",
            "Bcl2","Lef1","Foxo1","Foxp1","Il2ra","Selplg","Ctla4","Tgfb1",
            "Lgals1","Gzmb","Ccr2","Il10","Tnfrsf18","Tnfrsf4","Icos",
            "Il1r2","Cd28","Tcf7","Ccr8","Ccr6","Ikzf2","Gpr183","Il4","Il21",
            "Batf","Maf","Sh2d1a","Pdcd1","Bcl6","Cxcr5")

cl_use = "SNN_harmony20_res.0.6" 
DotPlot(subset, features = markers, 
        assay = "RNA",
        group.by = cl_use) +
  coord_flip() +
  scale_color_gradientn(colors = colorRampPalette(met.brewer("Johnson", direction = -1))(100))
```


```{r}
cl_use = "SNN_harmony20_res.0.6" 
subset = SetIdent(subset, value = cl_use)
mk_subset_res.6 = wilcoxauc(subset, group_by = cl_use, seurat_assay = "RNA")
mk_subset_res.6$pct_diff = mk_subset_res.6$pct_in - mk_subset_res.6$pct_out
View(mk_subset_res.6)
```


```{r fig.width=6, fig.height=8}
treg_mk = c("Foxp3","Prdm1","Klf2","Sell","S1pr1","Ccr7","Smad7",
            "Bcl2","Lef1","Il7r","Il2ra","Selplg","Tgfb1","Ctla4",
            "Ikzf2","Icos","Tnfrsf18","Nrp1","Gzmb","Ccr2","Il10")

cl_use = "SNN_harmony20_res.0.6" 
DotPlot(subset, features = treg_mk, 
        assay = "RNA",
        group.by = cl_use) +
  coord_flip() +
  scale_color_gradientn(colors = colorRampPalette(met.brewer("Johnson", direction = -1))(100))
```


```{r fig.width=6, fig.height=8}
degs_c8 = c("Ifi203","Ifit1","Ifi206","Ifi208","Ifit3","Ifi213",
            "Slfn8","Slfn1","Slfn5")

degs_c7 = c("Ikzf2","Tnfaip3","Zfp36l1","Rel","Ahnak","Btg1",
            "Skil","Dusp4","Tgif1","Cd83","Nt5e","Nr4a3")

degs_c3 = c("Capg","Cd74","Tnfrsf4","Cd83","Capn3","Vim",
            "Izumo1r","Cd52","Ifi27l2a","Ikzf2")

cl_use = "SNN_harmony20_res.0.6" 
DotPlot(subset, features = degs_c8, 
        assay = "RNA",
        group.by = cl_use) +
  coord_flip() +
  scale_color_gradientn(colors = colorRampPalette(met.brewer("Johnson", direction = -1))(100))
```


```{r fig.width=6, fig.height=5}
DimPlot(subset, group.by = c("SNN_harmony20_res.0.6"), 
        pt.size = 0.8, label = T, label.size = 12, cols = pal)
```


```{r}
cl_use = "SNN_harmony20_res.0.6" 
subset = SetIdent(subset, value = cl_use)

degs_13 = wilcoxauc(subset, group_by = cl_use, 
                   seurat_assay = "RNA", groups_use = c(1,3))
degs_13$pct_diff = degs_13$pct_in - degs_13$pct_out
View(degs_13)

degs_03 = wilcoxauc(subset, group_by = cl_use, 
                   seurat_assay = "RNA", groups_use = c(0,3))
degs_03$pct_diff = degs_03$pct_in - degs_03$pct_out
View(degs_03)

degs_07 = wilcoxauc(subset, group_by = cl_use, 
                   seurat_assay = "RNA", groups_use = c(0,7))
degs_07$pct_diff = degs_07$pct_in - degs_07$pct_out
View(degs_07)

degs_37 = wilcoxauc(subset, group_by = cl_use, 
                   seurat_assay = "RNA", groups_use = c(3,7))
degs_37$pct_diff = degs_37$pct_in - degs_37$pct_out
View(degs_37)
```


```{r}
cl_use = "SNN_harmony20_res.0.6" 
subset = SetIdent(subset, value = cl_use)

degs_tfh = wilcoxauc(subset, group_by = cl_use, 
                   seurat_assay = "RNA", groups_use = c(2,5))
degs_tfh$pct_diff = degs_tfh$pct_in - degs_tfh$pct_out
View(degs_tfh)

mk_tfr_treg = wilcoxauc(subset, group_by = cl_use, 
                        seurat_assay = "RNA", groups_use = c(1,4))
mk_tfr_treg$pct_diff = mk_tfr_treg$pct_in - mk_tfr_treg$pct_out
View(mk_tfr_treg)
```


```{r}
# save DEGs between Tfh Fol and GC
write.csv(degs_tfh, row.names = T,
          file = "/Users/maria/OneDrive/Documentos/iMM/analysis/results/DEGs/degs_tfh_fol_gc.csv")

# save DEGs between Tfr and effector Treg
write.csv(mk_tfr_treg, row.names = T,
          file = "/Users/maria/OneDrive/Documentos/iMM/analysis/results/DEGs/degs_tfr_treg.csv")
```


```{r}
subcelltype_df = c(
  "0" = "Treg naive",
  "1" = "eTreg",
  "2" = "Tfh",
  "3" = "Treg_2",
  "4" = "Tfr",
  "5" = "Tfh",
  "6" = "Tfr_1",
  "7" = "Treg_1",
  "8" = "Treg_3"
)

subset$cluster_celltype = unname(subcelltype_df[subset$SNN_harmony20_res.0.6])
```


```{r fig.width=12, fig.height=5}
DimPlot(subset, group.by = c("SNN_harmony20_res.0.6", "cluster_celltype"), 
        pt.size = 1, label.size = 8, cols = met.brewer("Klimt", 9), ncol = 2)
```

```{r}
mk_tfr_tfh = wilcoxauc(subset, group_by = "cluster_celltype", 
                        seurat_assay = "RNA", groups_use = c("Tfh","Tfr"))
mk_tfr_tfh$pct_diff = mk_tfr_tfh$pct_in - mk_tfr_tfh$pct_out
View(mk_tfr_tfh)
```


```{r}
# save DEGs between Tfr and Tfh (Fol + GC)
write.csv(mk_tfr_tfh, row.names = T,
          file = "/Users/maria/OneDrive/Documentos/iMM/analysis/results/DEGs/degs_tfr_tfh.csv")
```


```{r fig.width=25, fig.height=20}
FeaturePlot(subset, features = c("Foxp3","Cxcr5","Il2ra","Il1r2",
                                    "Klf2","Ccr7","Sell","Lef1",
                                    "Ctla4","Ccr2","Gzmb","Icos",
                                    "Tigit","Sh2d1a","Pdcd1","Bcl6"), 
            order=T, pt.size = 0.5, ncol = 4)
```


```{r}
subannot_df = c(
  "0" = "Treg naive",
  "1" = "eTreg",
  "2" = "Tfh Fol",
  "3" = "Treg_2",
  "4" = "Tfr",
  "5" = "GC-Tfh",
  "6" = "Tfr_1",
  "7" = "Treg_1",
  "8" = "Treg_3"
)

subset$harmony_annot = unname(subannot_df[subset$SNN_harmony20_res.0.6])
```


```{r fig.width=12, fig.height=5}
DimPlot(subset, group.by = c("SNN_harmony20_res.0.6", "harmony_annot"), 
        pt.size = 1, label.size = 8, cols = pal, ncol = 2)
```


```{r}
head(subset@meta.data)
```



```{r}
saveRDS(subset, "/Users/maria/OneDrive/Documentos/iMM/analysis/results/RDS/harmony_subset_srat.RDS")
```

